name = "pcbvalues"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[vars]
WEBHOOK_AVATAR = "https://raw.githubusercontent.com/pcbvalues/pcbvalues.github.io/main/assets/icon.png"
WEBHOOK_USERNAME = "PcbValues Score Webhook - %%"
